version: "3.9"
services:

  db:
    image: mysql
    volumes:
      - src:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root_secret
        MYSQL_DATABASE: heyrieux_echecs
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: secret
        
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"   
    restart: always
    environment:  
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: heyrieux_echecs

volumes:
  src: {}